<?php
/**
 * Body
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EXMI Attendee API
 *
 * API to register attendees from Marketing Sources and Apptl Systems Backend
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Body Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Body implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'body';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'principal_actividad_fabricante' => 'bool',
'intereses_centros_entretenimiento' => 'bool',
'estado' => 'string',
'intereses_otros' => 'string',
'domicilio_numero' => 'string',
'intereses_accesorios' => 'bool',
'intereses_literas_medera' => 'bool',
'intereses_tapizados' => 'bool',
'nombre_empresa' => 'string',
'intereses_terraza_jardin' => 'bool',
'razon_social' => 'string',
'giro_otros' => 'string',
'giro_muebleria' => 'bool',
'cargo' => 'string',
'telefono' => 'string',
'ciudad_empresa' => 'string',
'intereses_cocinas' => 'bool',
'codigo_postal' => 'string',
'mercado_atiende_otros' => 'string',
'principal_actividad_mayoreo' => 'bool',
'giro_importador' => 'bool',
'intereses_textiles' => 'bool',
'colonia' => 'string',
'mercado_atiende_hospitalidad' => 'bool',
'intereses_iluminacion' => 'bool',
'intereses_arte_sacro' => 'bool',
'ciudad' => 'string',
'codigo_postal_empresa' => 'string',
'intereses_infantiles_juveniles' => 'bool',
'intereses_comedores' => 'bool',
'locale' => 'string',
'nombres' => 'string',
'giro_construccion' => 'bool',
'domicilio' => 'string',
'intereses_servicios' => 'bool',
'mercado_atiende_construccion' => 'bool',
'celular' => 'string',
'intereses_mueble_oficina' => 'bool',
'intereses_recamaras_literas' => 'bool',
'intereses_tapetes' => 'bool',
'intereses_colchones' => 'bool',
'intereses_mecedoras' => 'bool',
'giro_servicios' => 'bool',
'email' => 'string',
'apellidos' => 'string',
'principal_actividad_otros' => 'string',
'mercado_atiende_residencial' => 'bool',
'principal_actividad_broker_intermediario' => 'bool',
'principal_actividad_venta_publico' => 'bool',
'nacimiento' => 'string',
'pais' => 'string',
'giro_tienda_departamental' => 'bool',
'redes_sociales_url_empresa' => 'string',
'principal_actividad_construccion_hospitalidad' => 'bool',
'giro_exportador' => 'bool',
'sexo' => 'string',
'principal_actividad_distribuidor' => 'bool',
'www_empresa' => 'string',
'mercado_atiende_corporativo' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'principal_actividad_fabricante' => null,
'intereses_centros_entretenimiento' => null,
'estado' => null,
'intereses_otros' => null,
'domicilio_numero' => null,
'intereses_accesorios' => null,
'intereses_literas_medera' => null,
'intereses_tapizados' => null,
'nombre_empresa' => null,
'intereses_terraza_jardin' => null,
'razon_social' => null,
'giro_otros' => null,
'giro_muebleria' => null,
'cargo' => null,
'telefono' => null,
'ciudad_empresa' => null,
'intereses_cocinas' => null,
'codigo_postal' => null,
'mercado_atiende_otros' => null,
'principal_actividad_mayoreo' => null,
'giro_importador' => null,
'intereses_textiles' => null,
'colonia' => null,
'mercado_atiende_hospitalidad' => null,
'intereses_iluminacion' => null,
'intereses_arte_sacro' => null,
'ciudad' => null,
'codigo_postal_empresa' => null,
'intereses_infantiles_juveniles' => null,
'intereses_comedores' => null,
'locale' => null,
'nombres' => null,
'giro_construccion' => null,
'domicilio' => null,
'intereses_servicios' => null,
'mercado_atiende_construccion' => null,
'celular' => null,
'intereses_mueble_oficina' => null,
'intereses_recamaras_literas' => null,
'intereses_tapetes' => null,
'intereses_colchones' => null,
'intereses_mecedoras' => null,
'giro_servicios' => null,
'email' => null,
'apellidos' => null,
'principal_actividad_otros' => null,
'mercado_atiende_residencial' => null,
'principal_actividad_broker_intermediario' => null,
'principal_actividad_venta_publico' => null,
'nacimiento' => null,
'pais' => null,
'giro_tienda_departamental' => null,
'redes_sociales_url_empresa' => null,
'principal_actividad_construccion_hospitalidad' => null,
'giro_exportador' => null,
'sexo' => null,
'principal_actividad_distribuidor' => null,
'www_empresa' => null,
'mercado_atiende_corporativo' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'principal_actividad_fabricante' => 'principalActividadFabricante',
'intereses_centros_entretenimiento' => 'interesesCentrosEntretenimiento',
'estado' => 'estado',
'intereses_otros' => 'interesesOtros',
'domicilio_numero' => 'domicilioNumero',
'intereses_accesorios' => 'interesesAccesorios',
'intereses_literas_medera' => 'interesesLiterasMedera',
'intereses_tapizados' => 'interesesTapizados',
'nombre_empresa' => 'nombreEmpresa',
'intereses_terraza_jardin' => 'interesesTerrazaJardin',
'razon_social' => 'razonSocial',
'giro_otros' => 'giroOtros',
'giro_muebleria' => 'giroMuebleria',
'cargo' => 'cargo',
'telefono' => 'telefono',
'ciudad_empresa' => 'ciudadEmpresa',
'intereses_cocinas' => 'interesesCocinas',
'codigo_postal' => 'codigoPostal',
'mercado_atiende_otros' => 'mercadoAtiendeOtros',
'principal_actividad_mayoreo' => 'principalActividadMayoreo',
'giro_importador' => 'giroImportador',
'intereses_textiles' => 'interesesTextiles',
'colonia' => 'colonia',
'mercado_atiende_hospitalidad' => 'mercadoAtiendeHospitalidad',
'intereses_iluminacion' => 'interesesIluminacion',
'intereses_arte_sacro' => 'interesesArteSacro',
'ciudad' => 'ciudad',
'codigo_postal_empresa' => 'codigoPostalEmpresa',
'intereses_infantiles_juveniles' => 'interesesInfantilesJuveniles',
'intereses_comedores' => 'interesesComedores',
'locale' => 'locale',
'nombres' => 'nombres',
'giro_construccion' => 'giroConstruccion',
'domicilio' => 'domicilio',
'intereses_servicios' => 'interesesServicios',
'mercado_atiende_construccion' => 'mercadoAtiendeConstruccion',
'celular' => 'celular',
'intereses_mueble_oficina' => 'interesesMuebleOficina',
'intereses_recamaras_literas' => 'interesesRecamarasLiteras',
'intereses_tapetes' => 'interesesTapetes',
'intereses_colchones' => 'interesesColchones',
'intereses_mecedoras' => 'interesesMecedoras',
'giro_servicios' => 'giroServicios',
'email' => 'email',
'apellidos' => 'apellidos',
'principal_actividad_otros' => 'principalActividadOtros',
'mercado_atiende_residencial' => 'mercadoAtiendeResidencial',
'principal_actividad_broker_intermediario' => 'principalActividadBrokerIntermediario',
'principal_actividad_venta_publico' => 'principalActividadVentaPublico',
'nacimiento' => 'nacimiento',
'pais' => 'pais',
'giro_tienda_departamental' => 'giroTiendaDepartamental',
'redes_sociales_url_empresa' => 'redesSocialesUrlEmpresa',
'principal_actividad_construccion_hospitalidad' => 'principalActividadConstruccionHospitalidad',
'giro_exportador' => 'giroExportador',
'sexo' => 'sexo',
'principal_actividad_distribuidor' => 'principalActividadDistribuidor',
'www_empresa' => 'wwwEmpresa',
'mercado_atiende_corporativo' => 'mercadoAtiendeCorporativo'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'principal_actividad_fabricante' => 'setPrincipalActividadFabricante',
'intereses_centros_entretenimiento' => 'setInteresesCentrosEntretenimiento',
'estado' => 'setEstado',
'intereses_otros' => 'setInteresesOtros',
'domicilio_numero' => 'setDomicilioNumero',
'intereses_accesorios' => 'setInteresesAccesorios',
'intereses_literas_medera' => 'setInteresesLiterasMedera',
'intereses_tapizados' => 'setInteresesTapizados',
'nombre_empresa' => 'setNombreEmpresa',
'intereses_terraza_jardin' => 'setInteresesTerrazaJardin',
'razon_social' => 'setRazonSocial',
'giro_otros' => 'setGiroOtros',
'giro_muebleria' => 'setGiroMuebleria',
'cargo' => 'setCargo',
'telefono' => 'setTelefono',
'ciudad_empresa' => 'setCiudadEmpresa',
'intereses_cocinas' => 'setInteresesCocinas',
'codigo_postal' => 'setCodigoPostal',
'mercado_atiende_otros' => 'setMercadoAtiendeOtros',
'principal_actividad_mayoreo' => 'setPrincipalActividadMayoreo',
'giro_importador' => 'setGiroImportador',
'intereses_textiles' => 'setInteresesTextiles',
'colonia' => 'setColonia',
'mercado_atiende_hospitalidad' => 'setMercadoAtiendeHospitalidad',
'intereses_iluminacion' => 'setInteresesIluminacion',
'intereses_arte_sacro' => 'setInteresesArteSacro',
'ciudad' => 'setCiudad',
'codigo_postal_empresa' => 'setCodigoPostalEmpresa',
'intereses_infantiles_juveniles' => 'setInteresesInfantilesJuveniles',
'intereses_comedores' => 'setInteresesComedores',
'locale' => 'setLocale',
'nombres' => 'setNombres',
'giro_construccion' => 'setGiroConstruccion',
'domicilio' => 'setDomicilio',
'intereses_servicios' => 'setInteresesServicios',
'mercado_atiende_construccion' => 'setMercadoAtiendeConstruccion',
'celular' => 'setCelular',
'intereses_mueble_oficina' => 'setInteresesMuebleOficina',
'intereses_recamaras_literas' => 'setInteresesRecamarasLiteras',
'intereses_tapetes' => 'setInteresesTapetes',
'intereses_colchones' => 'setInteresesColchones',
'intereses_mecedoras' => 'setInteresesMecedoras',
'giro_servicios' => 'setGiroServicios',
'email' => 'setEmail',
'apellidos' => 'setApellidos',
'principal_actividad_otros' => 'setPrincipalActividadOtros',
'mercado_atiende_residencial' => 'setMercadoAtiendeResidencial',
'principal_actividad_broker_intermediario' => 'setPrincipalActividadBrokerIntermediario',
'principal_actividad_venta_publico' => 'setPrincipalActividadVentaPublico',
'nacimiento' => 'setNacimiento',
'pais' => 'setPais',
'giro_tienda_departamental' => 'setGiroTiendaDepartamental',
'redes_sociales_url_empresa' => 'setRedesSocialesUrlEmpresa',
'principal_actividad_construccion_hospitalidad' => 'setPrincipalActividadConstruccionHospitalidad',
'giro_exportador' => 'setGiroExportador',
'sexo' => 'setSexo',
'principal_actividad_distribuidor' => 'setPrincipalActividadDistribuidor',
'www_empresa' => 'setWwwEmpresa',
'mercado_atiende_corporativo' => 'setMercadoAtiendeCorporativo'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'principal_actividad_fabricante' => 'getPrincipalActividadFabricante',
'intereses_centros_entretenimiento' => 'getInteresesCentrosEntretenimiento',
'estado' => 'getEstado',
'intereses_otros' => 'getInteresesOtros',
'domicilio_numero' => 'getDomicilioNumero',
'intereses_accesorios' => 'getInteresesAccesorios',
'intereses_literas_medera' => 'getInteresesLiterasMedera',
'intereses_tapizados' => 'getInteresesTapizados',
'nombre_empresa' => 'getNombreEmpresa',
'intereses_terraza_jardin' => 'getInteresesTerrazaJardin',
'razon_social' => 'getRazonSocial',
'giro_otros' => 'getGiroOtros',
'giro_muebleria' => 'getGiroMuebleria',
'cargo' => 'getCargo',
'telefono' => 'getTelefono',
'ciudad_empresa' => 'getCiudadEmpresa',
'intereses_cocinas' => 'getInteresesCocinas',
'codigo_postal' => 'getCodigoPostal',
'mercado_atiende_otros' => 'getMercadoAtiendeOtros',
'principal_actividad_mayoreo' => 'getPrincipalActividadMayoreo',
'giro_importador' => 'getGiroImportador',
'intereses_textiles' => 'getInteresesTextiles',
'colonia' => 'getColonia',
'mercado_atiende_hospitalidad' => 'getMercadoAtiendeHospitalidad',
'intereses_iluminacion' => 'getInteresesIluminacion',
'intereses_arte_sacro' => 'getInteresesArteSacro',
'ciudad' => 'getCiudad',
'codigo_postal_empresa' => 'getCodigoPostalEmpresa',
'intereses_infantiles_juveniles' => 'getInteresesInfantilesJuveniles',
'intereses_comedores' => 'getInteresesComedores',
'locale' => 'getLocale',
'nombres' => 'getNombres',
'giro_construccion' => 'getGiroConstruccion',
'domicilio' => 'getDomicilio',
'intereses_servicios' => 'getInteresesServicios',
'mercado_atiende_construccion' => 'getMercadoAtiendeConstruccion',
'celular' => 'getCelular',
'intereses_mueble_oficina' => 'getInteresesMuebleOficina',
'intereses_recamaras_literas' => 'getInteresesRecamarasLiteras',
'intereses_tapetes' => 'getInteresesTapetes',
'intereses_colchones' => 'getInteresesColchones',
'intereses_mecedoras' => 'getInteresesMecedoras',
'giro_servicios' => 'getGiroServicios',
'email' => 'getEmail',
'apellidos' => 'getApellidos',
'principal_actividad_otros' => 'getPrincipalActividadOtros',
'mercado_atiende_residencial' => 'getMercadoAtiendeResidencial',
'principal_actividad_broker_intermediario' => 'getPrincipalActividadBrokerIntermediario',
'principal_actividad_venta_publico' => 'getPrincipalActividadVentaPublico',
'nacimiento' => 'getNacimiento',
'pais' => 'getPais',
'giro_tienda_departamental' => 'getGiroTiendaDepartamental',
'redes_sociales_url_empresa' => 'getRedesSocialesUrlEmpresa',
'principal_actividad_construccion_hospitalidad' => 'getPrincipalActividadConstruccionHospitalidad',
'giro_exportador' => 'getGiroExportador',
'sexo' => 'getSexo',
'principal_actividad_distribuidor' => 'getPrincipalActividadDistribuidor',
'www_empresa' => 'getWwwEmpresa',
'mercado_atiende_corporativo' => 'getMercadoAtiendeCorporativo'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['principal_actividad_fabricante'] = isset($data['principal_actividad_fabricante']) ? $data['principal_actividad_fabricante'] : null;
        $this->container['intereses_centros_entretenimiento'] = isset($data['intereses_centros_entretenimiento']) ? $data['intereses_centros_entretenimiento'] : null;
        $this->container['estado'] = isset($data['estado']) ? $data['estado'] : null;
        $this->container['intereses_otros'] = isset($data['intereses_otros']) ? $data['intereses_otros'] : null;
        $this->container['domicilio_numero'] = isset($data['domicilio_numero']) ? $data['domicilio_numero'] : null;
        $this->container['intereses_accesorios'] = isset($data['intereses_accesorios']) ? $data['intereses_accesorios'] : null;
        $this->container['intereses_literas_medera'] = isset($data['intereses_literas_medera']) ? $data['intereses_literas_medera'] : null;
        $this->container['intereses_tapizados'] = isset($data['intereses_tapizados']) ? $data['intereses_tapizados'] : null;
        $this->container['nombre_empresa'] = isset($data['nombre_empresa']) ? $data['nombre_empresa'] : null;
        $this->container['intereses_terraza_jardin'] = isset($data['intereses_terraza_jardin']) ? $data['intereses_terraza_jardin'] : null;
        $this->container['razon_social'] = isset($data['razon_social']) ? $data['razon_social'] : null;
        $this->container['giro_otros'] = isset($data['giro_otros']) ? $data['giro_otros'] : null;
        $this->container['giro_muebleria'] = isset($data['giro_muebleria']) ? $data['giro_muebleria'] : null;
        $this->container['cargo'] = isset($data['cargo']) ? $data['cargo'] : null;
        $this->container['telefono'] = isset($data['telefono']) ? $data['telefono'] : null;
        $this->container['ciudad_empresa'] = isset($data['ciudad_empresa']) ? $data['ciudad_empresa'] : null;
        $this->container['intereses_cocinas'] = isset($data['intereses_cocinas']) ? $data['intereses_cocinas'] : null;
        $this->container['codigo_postal'] = isset($data['codigo_postal']) ? $data['codigo_postal'] : null;
        $this->container['mercado_atiende_otros'] = isset($data['mercado_atiende_otros']) ? $data['mercado_atiende_otros'] : null;
        $this->container['principal_actividad_mayoreo'] = isset($data['principal_actividad_mayoreo']) ? $data['principal_actividad_mayoreo'] : null;
        $this->container['giro_importador'] = isset($data['giro_importador']) ? $data['giro_importador'] : null;
        $this->container['intereses_textiles'] = isset($data['intereses_textiles']) ? $data['intereses_textiles'] : null;
        $this->container['colonia'] = isset($data['colonia']) ? $data['colonia'] : null;
        $this->container['mercado_atiende_hospitalidad'] = isset($data['mercado_atiende_hospitalidad']) ? $data['mercado_atiende_hospitalidad'] : null;
        $this->container['intereses_iluminacion'] = isset($data['intereses_iluminacion']) ? $data['intereses_iluminacion'] : null;
        $this->container['intereses_arte_sacro'] = isset($data['intereses_arte_sacro']) ? $data['intereses_arte_sacro'] : null;
        $this->container['ciudad'] = isset($data['ciudad']) ? $data['ciudad'] : null;
        $this->container['codigo_postal_empresa'] = isset($data['codigo_postal_empresa']) ? $data['codigo_postal_empresa'] : null;
        $this->container['intereses_infantiles_juveniles'] = isset($data['intereses_infantiles_juveniles']) ? $data['intereses_infantiles_juveniles'] : null;
        $this->container['intereses_comedores'] = isset($data['intereses_comedores']) ? $data['intereses_comedores'] : null;
        $this->container['locale'] = isset($data['locale']) ? $data['locale'] : null;
        $this->container['nombres'] = isset($data['nombres']) ? $data['nombres'] : null;
        $this->container['giro_construccion'] = isset($data['giro_construccion']) ? $data['giro_construccion'] : null;
        $this->container['domicilio'] = isset($data['domicilio']) ? $data['domicilio'] : null;
        $this->container['intereses_servicios'] = isset($data['intereses_servicios']) ? $data['intereses_servicios'] : null;
        $this->container['mercado_atiende_construccion'] = isset($data['mercado_atiende_construccion']) ? $data['mercado_atiende_construccion'] : null;
        $this->container['celular'] = isset($data['celular']) ? $data['celular'] : null;
        $this->container['intereses_mueble_oficina'] = isset($data['intereses_mueble_oficina']) ? $data['intereses_mueble_oficina'] : null;
        $this->container['intereses_recamaras_literas'] = isset($data['intereses_recamaras_literas']) ? $data['intereses_recamaras_literas'] : null;
        $this->container['intereses_tapetes'] = isset($data['intereses_tapetes']) ? $data['intereses_tapetes'] : null;
        $this->container['intereses_colchones'] = isset($data['intereses_colchones']) ? $data['intereses_colchones'] : null;
        $this->container['intereses_mecedoras'] = isset($data['intereses_mecedoras']) ? $data['intereses_mecedoras'] : null;
        $this->container['giro_servicios'] = isset($data['giro_servicios']) ? $data['giro_servicios'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['apellidos'] = isset($data['apellidos']) ? $data['apellidos'] : null;
        $this->container['principal_actividad_otros'] = isset($data['principal_actividad_otros']) ? $data['principal_actividad_otros'] : null;
        $this->container['mercado_atiende_residencial'] = isset($data['mercado_atiende_residencial']) ? $data['mercado_atiende_residencial'] : null;
        $this->container['principal_actividad_broker_intermediario'] = isset($data['principal_actividad_broker_intermediario']) ? $data['principal_actividad_broker_intermediario'] : null;
        $this->container['principal_actividad_venta_publico'] = isset($data['principal_actividad_venta_publico']) ? $data['principal_actividad_venta_publico'] : null;
        $this->container['nacimiento'] = isset($data['nacimiento']) ? $data['nacimiento'] : null;
        $this->container['pais'] = isset($data['pais']) ? $data['pais'] : null;
        $this->container['giro_tienda_departamental'] = isset($data['giro_tienda_departamental']) ? $data['giro_tienda_departamental'] : null;
        $this->container['redes_sociales_url_empresa'] = isset($data['redes_sociales_url_empresa']) ? $data['redes_sociales_url_empresa'] : null;
        $this->container['principal_actividad_construccion_hospitalidad'] = isset($data['principal_actividad_construccion_hospitalidad']) ? $data['principal_actividad_construccion_hospitalidad'] : null;
        $this->container['giro_exportador'] = isset($data['giro_exportador']) ? $data['giro_exportador'] : null;
        $this->container['sexo'] = isset($data['sexo']) ? $data['sexo'] : null;
        $this->container['principal_actividad_distribuidor'] = isset($data['principal_actividad_distribuidor']) ? $data['principal_actividad_distribuidor'] : null;
        $this->container['www_empresa'] = isset($data['www_empresa']) ? $data['www_empresa'] : null;
        $this->container['mercado_atiende_corporativo'] = isset($data['mercado_atiende_corporativo']) ? $data['mercado_atiende_corporativo'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets principal_actividad_fabricante
     *
     * @return bool
     */
    public function getPrincipalActividadFabricante()
    {
        return $this->container['principal_actividad_fabricante'];
    }

    /**
     * Sets principal_actividad_fabricante
     *
     * @param bool $principal_actividad_fabricante principal_actividad_fabricante
     *
     * @return $this
     */
    public function setPrincipalActividadFabricante($principal_actividad_fabricante)
    {
        $this->container['principal_actividad_fabricante'] = $principal_actividad_fabricante;

        return $this;
    }

    /**
     * Gets intereses_centros_entretenimiento
     *
     * @return bool
     */
    public function getInteresesCentrosEntretenimiento()
    {
        return $this->container['intereses_centros_entretenimiento'];
    }

    /**
     * Sets intereses_centros_entretenimiento
     *
     * @param bool $intereses_centros_entretenimiento intereses_centros_entretenimiento
     *
     * @return $this
     */
    public function setInteresesCentrosEntretenimiento($intereses_centros_entretenimiento)
    {
        $this->container['intereses_centros_entretenimiento'] = $intereses_centros_entretenimiento;

        return $this;
    }

    /**
     * Gets estado
     *
     * @return string
     */
    public function getEstado()
    {
        return $this->container['estado'];
    }

    /**
     * Sets estado
     *
     * @param string $estado estado
     *
     * @return $this
     */
    public function setEstado($estado)
    {
        $this->container['estado'] = $estado;

        return $this;
    }

    /**
     * Gets intereses_otros
     *
     * @return string
     */
    public function getInteresesOtros()
    {
        return $this->container['intereses_otros'];
    }

    /**
     * Sets intereses_otros
     *
     * @param string $intereses_otros intereses_otros
     *
     * @return $this
     */
    public function setInteresesOtros($intereses_otros)
    {
        $this->container['intereses_otros'] = $intereses_otros;

        return $this;
    }

    /**
     * Gets domicilio_numero
     *
     * @return string
     */
    public function getDomicilioNumero()
    {
        return $this->container['domicilio_numero'];
    }

    /**
     * Sets domicilio_numero
     *
     * @param string $domicilio_numero domicilio_numero
     *
     * @return $this
     */
    public function setDomicilioNumero($domicilio_numero)
    {
        $this->container['domicilio_numero'] = $domicilio_numero;

        return $this;
    }

    /**
     * Gets intereses_accesorios
     *
     * @return bool
     */
    public function getInteresesAccesorios()
    {
        return $this->container['intereses_accesorios'];
    }

    /**
     * Sets intereses_accesorios
     *
     * @param bool $intereses_accesorios intereses_accesorios
     *
     * @return $this
     */
    public function setInteresesAccesorios($intereses_accesorios)
    {
        $this->container['intereses_accesorios'] = $intereses_accesorios;

        return $this;
    }

    /**
     * Gets intereses_literas_medera
     *
     * @return bool
     */
    public function getInteresesLiterasMedera()
    {
        return $this->container['intereses_literas_medera'];
    }

    /**
     * Sets intereses_literas_medera
     *
     * @param bool $intereses_literas_medera intereses_literas_medera
     *
     * @return $this
     */
    public function setInteresesLiterasMedera($intereses_literas_medera)
    {
        $this->container['intereses_literas_medera'] = $intereses_literas_medera;

        return $this;
    }

    /**
     * Gets intereses_tapizados
     *
     * @return bool
     */
    public function getInteresesTapizados()
    {
        return $this->container['intereses_tapizados'];
    }

    /**
     * Sets intereses_tapizados
     *
     * @param bool $intereses_tapizados intereses_tapizados
     *
     * @return $this
     */
    public function setInteresesTapizados($intereses_tapizados)
    {
        $this->container['intereses_tapizados'] = $intereses_tapizados;

        return $this;
    }

    /**
     * Gets nombre_empresa
     *
     * @return string
     */
    public function getNombreEmpresa()
    {
        return $this->container['nombre_empresa'];
    }

    /**
     * Sets nombre_empresa
     *
     * @param string $nombre_empresa nombre_empresa
     *
     * @return $this
     */
    public function setNombreEmpresa($nombre_empresa)
    {
        $this->container['nombre_empresa'] = $nombre_empresa;

        return $this;
    }

    /**
     * Gets intereses_terraza_jardin
     *
     * @return bool
     */
    public function getInteresesTerrazaJardin()
    {
        return $this->container['intereses_terraza_jardin'];
    }

    /**
     * Sets intereses_terraza_jardin
     *
     * @param bool $intereses_terraza_jardin intereses_terraza_jardin
     *
     * @return $this
     */
    public function setInteresesTerrazaJardin($intereses_terraza_jardin)
    {
        $this->container['intereses_terraza_jardin'] = $intereses_terraza_jardin;

        return $this;
    }

    /**
     * Gets razon_social
     *
     * @return string
     */
    public function getRazonSocial()
    {
        return $this->container['razon_social'];
    }

    /**
     * Sets razon_social
     *
     * @param string $razon_social razon_social
     *
     * @return $this
     */
    public function setRazonSocial($razon_social)
    {
        $this->container['razon_social'] = $razon_social;

        return $this;
    }

    /**
     * Gets giro_otros
     *
     * @return string
     */
    public function getGiroOtros()
    {
        return $this->container['giro_otros'];
    }

    /**
     * Sets giro_otros
     *
     * @param string $giro_otros giro_otros
     *
     * @return $this
     */
    public function setGiroOtros($giro_otros)
    {
        $this->container['giro_otros'] = $giro_otros;

        return $this;
    }

    /**
     * Gets giro_muebleria
     *
     * @return bool
     */
    public function getGiroMuebleria()
    {
        return $this->container['giro_muebleria'];
    }

    /**
     * Sets giro_muebleria
     *
     * @param bool $giro_muebleria giro_muebleria
     *
     * @return $this
     */
    public function setGiroMuebleria($giro_muebleria)
    {
        $this->container['giro_muebleria'] = $giro_muebleria;

        return $this;
    }

    /**
     * Gets cargo
     *
     * @return string
     */
    public function getCargo()
    {
        return $this->container['cargo'];
    }

    /**
     * Sets cargo
     *
     * @param string $cargo cargo
     *
     * @return $this
     */
    public function setCargo($cargo)
    {
        $this->container['cargo'] = $cargo;

        return $this;
    }

    /**
     * Gets telefono
     *
     * @return string
     */
    public function getTelefono()
    {
        return $this->container['telefono'];
    }

    /**
     * Sets telefono
     *
     * @param string $telefono telefono
     *
     * @return $this
     */
    public function setTelefono($telefono)
    {
        $this->container['telefono'] = $telefono;

        return $this;
    }

    /**
     * Gets ciudad_empresa
     *
     * @return string
     */
    public function getCiudadEmpresa()
    {
        return $this->container['ciudad_empresa'];
    }

    /**
     * Sets ciudad_empresa
     *
     * @param string $ciudad_empresa ciudad_empresa
     *
     * @return $this
     */
    public function setCiudadEmpresa($ciudad_empresa)
    {
        $this->container['ciudad_empresa'] = $ciudad_empresa;

        return $this;
    }

    /**
     * Gets intereses_cocinas
     *
     * @return bool
     */
    public function getInteresesCocinas()
    {
        return $this->container['intereses_cocinas'];
    }

    /**
     * Sets intereses_cocinas
     *
     * @param bool $intereses_cocinas intereses_cocinas
     *
     * @return $this
     */
    public function setInteresesCocinas($intereses_cocinas)
    {
        $this->container['intereses_cocinas'] = $intereses_cocinas;

        return $this;
    }

    /**
     * Gets codigo_postal
     *
     * @return string
     */
    public function getCodigoPostal()
    {
        return $this->container['codigo_postal'];
    }

    /**
     * Sets codigo_postal
     *
     * @param string $codigo_postal codigo_postal
     *
     * @return $this
     */
    public function setCodigoPostal($codigo_postal)
    {
        $this->container['codigo_postal'] = $codigo_postal;

        return $this;
    }

    /**
     * Gets mercado_atiende_otros
     *
     * @return string
     */
    public function getMercadoAtiendeOtros()
    {
        return $this->container['mercado_atiende_otros'];
    }

    /**
     * Sets mercado_atiende_otros
     *
     * @param string $mercado_atiende_otros mercado_atiende_otros
     *
     * @return $this
     */
    public function setMercadoAtiendeOtros($mercado_atiende_otros)
    {
        $this->container['mercado_atiende_otros'] = $mercado_atiende_otros;

        return $this;
    }

    /**
     * Gets principal_actividad_mayoreo
     *
     * @return bool
     */
    public function getPrincipalActividadMayoreo()
    {
        return $this->container['principal_actividad_mayoreo'];
    }

    /**
     * Sets principal_actividad_mayoreo
     *
     * @param bool $principal_actividad_mayoreo principal_actividad_mayoreo
     *
     * @return $this
     */
    public function setPrincipalActividadMayoreo($principal_actividad_mayoreo)
    {
        $this->container['principal_actividad_mayoreo'] = $principal_actividad_mayoreo;

        return $this;
    }

    /**
     * Gets giro_importador
     *
     * @return bool
     */
    public function getGiroImportador()
    {
        return $this->container['giro_importador'];
    }

    /**
     * Sets giro_importador
     *
     * @param bool $giro_importador giro_importador
     *
     * @return $this
     */
    public function setGiroImportador($giro_importador)
    {
        $this->container['giro_importador'] = $giro_importador;

        return $this;
    }

    /**
     * Gets intereses_textiles
     *
     * @return bool
     */
    public function getInteresesTextiles()
    {
        return $this->container['intereses_textiles'];
    }

    /**
     * Sets intereses_textiles
     *
     * @param bool $intereses_textiles intereses_textiles
     *
     * @return $this
     */
    public function setInteresesTextiles($intereses_textiles)
    {
        $this->container['intereses_textiles'] = $intereses_textiles;

        return $this;
    }

    /**
     * Gets colonia
     *
     * @return string
     */
    public function getColonia()
    {
        return $this->container['colonia'];
    }

    /**
     * Sets colonia
     *
     * @param string $colonia colonia
     *
     * @return $this
     */
    public function setColonia($colonia)
    {
        $this->container['colonia'] = $colonia;

        return $this;
    }

    /**
     * Gets mercado_atiende_hospitalidad
     *
     * @return bool
     */
    public function getMercadoAtiendeHospitalidad()
    {
        return $this->container['mercado_atiende_hospitalidad'];
    }

    /**
     * Sets mercado_atiende_hospitalidad
     *
     * @param bool $mercado_atiende_hospitalidad mercado_atiende_hospitalidad
     *
     * @return $this
     */
    public function setMercadoAtiendeHospitalidad($mercado_atiende_hospitalidad)
    {
        $this->container['mercado_atiende_hospitalidad'] = $mercado_atiende_hospitalidad;

        return $this;
    }

    /**
     * Gets intereses_iluminacion
     *
     * @return bool
     */
    public function getInteresesIluminacion()
    {
        return $this->container['intereses_iluminacion'];
    }

    /**
     * Sets intereses_iluminacion
     *
     * @param bool $intereses_iluminacion intereses_iluminacion
     *
     * @return $this
     */
    public function setInteresesIluminacion($intereses_iluminacion)
    {
        $this->container['intereses_iluminacion'] = $intereses_iluminacion;

        return $this;
    }

    /**
     * Gets intereses_arte_sacro
     *
     * @return bool
     */
    public function getInteresesArteSacro()
    {
        return $this->container['intereses_arte_sacro'];
    }

    /**
     * Sets intereses_arte_sacro
     *
     * @param bool $intereses_arte_sacro intereses_arte_sacro
     *
     * @return $this
     */
    public function setInteresesArteSacro($intereses_arte_sacro)
    {
        $this->container['intereses_arte_sacro'] = $intereses_arte_sacro;

        return $this;
    }

    /**
     * Gets ciudad
     *
     * @return string
     */
    public function getCiudad()
    {
        return $this->container['ciudad'];
    }

    /**
     * Sets ciudad
     *
     * @param string $ciudad ciudad
     *
     * @return $this
     */
    public function setCiudad($ciudad)
    {
        $this->container['ciudad'] = $ciudad;

        return $this;
    }

    /**
     * Gets codigo_postal_empresa
     *
     * @return string
     */
    public function getCodigoPostalEmpresa()
    {
        return $this->container['codigo_postal_empresa'];
    }

    /**
     * Sets codigo_postal_empresa
     *
     * @param string $codigo_postal_empresa codigo_postal_empresa
     *
     * @return $this
     */
    public function setCodigoPostalEmpresa($codigo_postal_empresa)
    {
        $this->container['codigo_postal_empresa'] = $codigo_postal_empresa;

        return $this;
    }

    /**
     * Gets intereses_infantiles_juveniles
     *
     * @return bool
     */
    public function getInteresesInfantilesJuveniles()
    {
        return $this->container['intereses_infantiles_juveniles'];
    }

    /**
     * Sets intereses_infantiles_juveniles
     *
     * @param bool $intereses_infantiles_juveniles intereses_infantiles_juveniles
     *
     * @return $this
     */
    public function setInteresesInfantilesJuveniles($intereses_infantiles_juveniles)
    {
        $this->container['intereses_infantiles_juveniles'] = $intereses_infantiles_juveniles;

        return $this;
    }

    /**
     * Gets intereses_comedores
     *
     * @return bool
     */
    public function getInteresesComedores()
    {
        return $this->container['intereses_comedores'];
    }

    /**
     * Sets intereses_comedores
     *
     * @param bool $intereses_comedores intereses_comedores
     *
     * @return $this
     */
    public function setInteresesComedores($intereses_comedores)
    {
        $this->container['intereses_comedores'] = $intereses_comedores;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string $locale locale
     *
     * @return $this
     */
    public function setLocale($locale)
    {
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets nombres
     *
     * @return string
     */
    public function getNombres()
    {
        return $this->container['nombres'];
    }

    /**
     * Sets nombres
     *
     * @param string $nombres nombres
     *
     * @return $this
     */
    public function setNombres($nombres)
    {
        $this->container['nombres'] = $nombres;

        return $this;
    }

    /**
     * Gets giro_construccion
     *
     * @return bool
     */
    public function getGiroConstruccion()
    {
        return $this->container['giro_construccion'];
    }

    /**
     * Sets giro_construccion
     *
     * @param bool $giro_construccion giro_construccion
     *
     * @return $this
     */
    public function setGiroConstruccion($giro_construccion)
    {
        $this->container['giro_construccion'] = $giro_construccion;

        return $this;
    }

    /**
     * Gets domicilio
     *
     * @return string
     */
    public function getDomicilio()
    {
        return $this->container['domicilio'];
    }

    /**
     * Sets domicilio
     *
     * @param string $domicilio domicilio
     *
     * @return $this
     */
    public function setDomicilio($domicilio)
    {
        $this->container['domicilio'] = $domicilio;

        return $this;
    }

    /**
     * Gets intereses_servicios
     *
     * @return bool
     */
    public function getInteresesServicios()
    {
        return $this->container['intereses_servicios'];
    }

    /**
     * Sets intereses_servicios
     *
     * @param bool $intereses_servicios intereses_servicios
     *
     * @return $this
     */
    public function setInteresesServicios($intereses_servicios)
    {
        $this->container['intereses_servicios'] = $intereses_servicios;

        return $this;
    }

    /**
     * Gets mercado_atiende_construccion
     *
     * @return bool
     */
    public function getMercadoAtiendeConstruccion()
    {
        return $this->container['mercado_atiende_construccion'];
    }

    /**
     * Sets mercado_atiende_construccion
     *
     * @param bool $mercado_atiende_construccion mercado_atiende_construccion
     *
     * @return $this
     */
    public function setMercadoAtiendeConstruccion($mercado_atiende_construccion)
    {
        $this->container['mercado_atiende_construccion'] = $mercado_atiende_construccion;

        return $this;
    }

    /**
     * Gets celular
     *
     * @return string
     */
    public function getCelular()
    {
        return $this->container['celular'];
    }

    /**
     * Sets celular
     *
     * @param string $celular celular
     *
     * @return $this
     */
    public function setCelular($celular)
    {
        $this->container['celular'] = $celular;

        return $this;
    }

    /**
     * Gets intereses_mueble_oficina
     *
     * @return bool
     */
    public function getInteresesMuebleOficina()
    {
        return $this->container['intereses_mueble_oficina'];
    }

    /**
     * Sets intereses_mueble_oficina
     *
     * @param bool $intereses_mueble_oficina intereses_mueble_oficina
     *
     * @return $this
     */
    public function setInteresesMuebleOficina($intereses_mueble_oficina)
    {
        $this->container['intereses_mueble_oficina'] = $intereses_mueble_oficina;

        return $this;
    }

    /**
     * Gets intereses_recamaras_literas
     *
     * @return bool
     */
    public function getInteresesRecamarasLiteras()
    {
        return $this->container['intereses_recamaras_literas'];
    }

    /**
     * Sets intereses_recamaras_literas
     *
     * @param bool $intereses_recamaras_literas intereses_recamaras_literas
     *
     * @return $this
     */
    public function setInteresesRecamarasLiteras($intereses_recamaras_literas)
    {
        $this->container['intereses_recamaras_literas'] = $intereses_recamaras_literas;

        return $this;
    }

    /**
     * Gets intereses_tapetes
     *
     * @return bool
     */
    public function getInteresesTapetes()
    {
        return $this->container['intereses_tapetes'];
    }

    /**
     * Sets intereses_tapetes
     *
     * @param bool $intereses_tapetes intereses_tapetes
     *
     * @return $this
     */
    public function setInteresesTapetes($intereses_tapetes)
    {
        $this->container['intereses_tapetes'] = $intereses_tapetes;

        return $this;
    }

    /**
     * Gets intereses_colchones
     *
     * @return bool
     */
    public function getInteresesColchones()
    {
        return $this->container['intereses_colchones'];
    }

    /**
     * Sets intereses_colchones
     *
     * @param bool $intereses_colchones intereses_colchones
     *
     * @return $this
     */
    public function setInteresesColchones($intereses_colchones)
    {
        $this->container['intereses_colchones'] = $intereses_colchones;

        return $this;
    }

    /**
     * Gets intereses_mecedoras
     *
     * @return bool
     */
    public function getInteresesMecedoras()
    {
        return $this->container['intereses_mecedoras'];
    }

    /**
     * Sets intereses_mecedoras
     *
     * @param bool $intereses_mecedoras intereses_mecedoras
     *
     * @return $this
     */
    public function setInteresesMecedoras($intereses_mecedoras)
    {
        $this->container['intereses_mecedoras'] = $intereses_mecedoras;

        return $this;
    }

    /**
     * Gets giro_servicios
     *
     * @return bool
     */
    public function getGiroServicios()
    {
        return $this->container['giro_servicios'];
    }

    /**
     * Sets giro_servicios
     *
     * @param bool $giro_servicios giro_servicios
     *
     * @return $this
     */
    public function setGiroServicios($giro_servicios)
    {
        $this->container['giro_servicios'] = $giro_servicios;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets apellidos
     *
     * @return string
     */
    public function getApellidos()
    {
        return $this->container['apellidos'];
    }

    /**
     * Sets apellidos
     *
     * @param string $apellidos apellidos
     *
     * @return $this
     */
    public function setApellidos($apellidos)
    {
        $this->container['apellidos'] = $apellidos;

        return $this;
    }

    /**
     * Gets principal_actividad_otros
     *
     * @return string
     */
    public function getPrincipalActividadOtros()
    {
        return $this->container['principal_actividad_otros'];
    }

    /**
     * Sets principal_actividad_otros
     *
     * @param string $principal_actividad_otros principal_actividad_otros
     *
     * @return $this
     */
    public function setPrincipalActividadOtros($principal_actividad_otros)
    {
        $this->container['principal_actividad_otros'] = $principal_actividad_otros;

        return $this;
    }

    /**
     * Gets mercado_atiende_residencial
     *
     * @return bool
     */
    public function getMercadoAtiendeResidencial()
    {
        return $this->container['mercado_atiende_residencial'];
    }

    /**
     * Sets mercado_atiende_residencial
     *
     * @param bool $mercado_atiende_residencial mercado_atiende_residencial
     *
     * @return $this
     */
    public function setMercadoAtiendeResidencial($mercado_atiende_residencial)
    {
        $this->container['mercado_atiende_residencial'] = $mercado_atiende_residencial;

        return $this;
    }

    /**
     * Gets principal_actividad_broker_intermediario
     *
     * @return bool
     */
    public function getPrincipalActividadBrokerIntermediario()
    {
        return $this->container['principal_actividad_broker_intermediario'];
    }

    /**
     * Sets principal_actividad_broker_intermediario
     *
     * @param bool $principal_actividad_broker_intermediario principal_actividad_broker_intermediario
     *
     * @return $this
     */
    public function setPrincipalActividadBrokerIntermediario($principal_actividad_broker_intermediario)
    {
        $this->container['principal_actividad_broker_intermediario'] = $principal_actividad_broker_intermediario;

        return $this;
    }

    /**
     * Gets principal_actividad_venta_publico
     *
     * @return bool
     */
    public function getPrincipalActividadVentaPublico()
    {
        return $this->container['principal_actividad_venta_publico'];
    }

    /**
     * Sets principal_actividad_venta_publico
     *
     * @param bool $principal_actividad_venta_publico principal_actividad_venta_publico
     *
     * @return $this
     */
    public function setPrincipalActividadVentaPublico($principal_actividad_venta_publico)
    {
        $this->container['principal_actividad_venta_publico'] = $principal_actividad_venta_publico;

        return $this;
    }

    /**
     * Gets nacimiento
     *
     * @return string
     */
    public function getNacimiento()
    {
        return $this->container['nacimiento'];
    }

    /**
     * Sets nacimiento
     *
     * @param string $nacimiento nacimiento
     *
     * @return $this
     */
    public function setNacimiento($nacimiento)
    {
        $this->container['nacimiento'] = $nacimiento;

        return $this;
    }

    /**
     * Gets pais
     *
     * @return string
     */
    public function getPais()
    {
        return $this->container['pais'];
    }

    /**
     * Sets pais
     *
     * @param string $pais pais
     *
     * @return $this
     */
    public function setPais($pais)
    {
        $this->container['pais'] = $pais;

        return $this;
    }

    /**
     * Gets giro_tienda_departamental
     *
     * @return bool
     */
    public function getGiroTiendaDepartamental()
    {
        return $this->container['giro_tienda_departamental'];
    }

    /**
     * Sets giro_tienda_departamental
     *
     * @param bool $giro_tienda_departamental giro_tienda_departamental
     *
     * @return $this
     */
    public function setGiroTiendaDepartamental($giro_tienda_departamental)
    {
        $this->container['giro_tienda_departamental'] = $giro_tienda_departamental;

        return $this;
    }

    /**
     * Gets redes_sociales_url_empresa
     *
     * @return string
     */
    public function getRedesSocialesUrlEmpresa()
    {
        return $this->container['redes_sociales_url_empresa'];
    }

    /**
     * Sets redes_sociales_url_empresa
     *
     * @param string $redes_sociales_url_empresa redes_sociales_url_empresa
     *
     * @return $this
     */
    public function setRedesSocialesUrlEmpresa($redes_sociales_url_empresa)
    {
        $this->container['redes_sociales_url_empresa'] = $redes_sociales_url_empresa;

        return $this;
    }

    /**
     * Gets principal_actividad_construccion_hospitalidad
     *
     * @return bool
     */
    public function getPrincipalActividadConstruccionHospitalidad()
    {
        return $this->container['principal_actividad_construccion_hospitalidad'];
    }

    /**
     * Sets principal_actividad_construccion_hospitalidad
     *
     * @param bool $principal_actividad_construccion_hospitalidad principal_actividad_construccion_hospitalidad
     *
     * @return $this
     */
    public function setPrincipalActividadConstruccionHospitalidad($principal_actividad_construccion_hospitalidad)
    {
        $this->container['principal_actividad_construccion_hospitalidad'] = $principal_actividad_construccion_hospitalidad;

        return $this;
    }

    /**
     * Gets giro_exportador
     *
     * @return bool
     */
    public function getGiroExportador()
    {
        return $this->container['giro_exportador'];
    }

    /**
     * Sets giro_exportador
     *
     * @param bool $giro_exportador giro_exportador
     *
     * @return $this
     */
    public function setGiroExportador($giro_exportador)
    {
        $this->container['giro_exportador'] = $giro_exportador;

        return $this;
    }

    /**
     * Gets sexo
     *
     * @return string
     */
    public function getSexo()
    {
        return $this->container['sexo'];
    }

    /**
     * Sets sexo
     *
     * @param string $sexo sexo
     *
     * @return $this
     */
    public function setSexo($sexo)
    {
        $this->container['sexo'] = $sexo;

        return $this;
    }

    /**
     * Gets principal_actividad_distribuidor
     *
     * @return bool
     */
    public function getPrincipalActividadDistribuidor()
    {
        return $this->container['principal_actividad_distribuidor'];
    }

    /**
     * Sets principal_actividad_distribuidor
     *
     * @param bool $principal_actividad_distribuidor principal_actividad_distribuidor
     *
     * @return $this
     */
    public function setPrincipalActividadDistribuidor($principal_actividad_distribuidor)
    {
        $this->container['principal_actividad_distribuidor'] = $principal_actividad_distribuidor;

        return $this;
    }

    /**
     * Gets www_empresa
     *
     * @return string
     */
    public function getWwwEmpresa()
    {
        return $this->container['www_empresa'];
    }

    /**
     * Sets www_empresa
     *
     * @param string $www_empresa www_empresa
     *
     * @return $this
     */
    public function setWwwEmpresa($www_empresa)
    {
        $this->container['www_empresa'] = $www_empresa;

        return $this;
    }

    /**
     * Gets mercado_atiende_corporativo
     *
     * @return bool
     */
    public function getMercadoAtiendeCorporativo()
    {
        return $this->container['mercado_atiende_corporativo'];
    }

    /**
     * Sets mercado_atiende_corporativo
     *
     * @param bool $mercado_atiende_corporativo mercado_atiende_corporativo
     *
     * @return $this
     */
    public function setMercadoAtiendeCorporativo($mercado_atiende_corporativo)
    {
        $this->container['mercado_atiende_corporativo'] = $mercado_atiende_corporativo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
