<?php
/**
 * BodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EXMI Attendee API
 *
 * API to register attendees from Marketing Sources and Apptl Systems Backend
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BodyTest Class Doc Comment
 *
 * @category    Class
 * @description Body
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Body"
     */
    public function testBody()
    {
    }

    /**
     * Test attribute "principal_actividad_fabricante"
     */
    public function testPropertyPrincipalActividadFabricante()
    {
    }

    /**
     * Test attribute "intereses_centros_entretenimiento"
     */
    public function testPropertyInteresesCentrosEntretenimiento()
    {
    }

    /**
     * Test attribute "estado"
     */
    public function testPropertyEstado()
    {
    }

    /**
     * Test attribute "intereses_otros"
     */
    public function testPropertyInteresesOtros()
    {
    }

    /**
     * Test attribute "domicilio_numero"
     */
    public function testPropertyDomicilioNumero()
    {
    }

    /**
     * Test attribute "intereses_accesorios"
     */
    public function testPropertyInteresesAccesorios()
    {
    }

    /**
     * Test attribute "intereses_literas_medera"
     */
    public function testPropertyInteresesLiterasMedera()
    {
    }

    /**
     * Test attribute "intereses_tapizados"
     */
    public function testPropertyInteresesTapizados()
    {
    }

    /**
     * Test attribute "nombre_empresa"
     */
    public function testPropertyNombreEmpresa()
    {
    }

    /**
     * Test attribute "intereses_terraza_jardin"
     */
    public function testPropertyInteresesTerrazaJardin()
    {
    }

    /**
     * Test attribute "razon_social"
     */
    public function testPropertyRazonSocial()
    {
    }

    /**
     * Test attribute "giro_otros"
     */
    public function testPropertyGiroOtros()
    {
    }

    /**
     * Test attribute "giro_muebleria"
     */
    public function testPropertyGiroMuebleria()
    {
    }

    /**
     * Test attribute "cargo"
     */
    public function testPropertyCargo()
    {
    }

    /**
     * Test attribute "telefono"
     */
    public function testPropertyTelefono()
    {
    }

    /**
     * Test attribute "ciudad_empresa"
     */
    public function testPropertyCiudadEmpresa()
    {
    }

    /**
     * Test attribute "intereses_cocinas"
     */
    public function testPropertyInteresesCocinas()
    {
    }

    /**
     * Test attribute "codigo_postal"
     */
    public function testPropertyCodigoPostal()
    {
    }

    /**
     * Test attribute "mercado_atiende_otros"
     */
    public function testPropertyMercadoAtiendeOtros()
    {
    }

    /**
     * Test attribute "principal_actividad_mayoreo"
     */
    public function testPropertyPrincipalActividadMayoreo()
    {
    }

    /**
     * Test attribute "giro_importador"
     */
    public function testPropertyGiroImportador()
    {
    }

    /**
     * Test attribute "intereses_textiles"
     */
    public function testPropertyInteresesTextiles()
    {
    }

    /**
     * Test attribute "colonia"
     */
    public function testPropertyColonia()
    {
    }

    /**
     * Test attribute "mercado_atiende_hospitalidad"
     */
    public function testPropertyMercadoAtiendeHospitalidad()
    {
    }

    /**
     * Test attribute "intereses_iluminacion"
     */
    public function testPropertyInteresesIluminacion()
    {
    }

    /**
     * Test attribute "intereses_arte_sacro"
     */
    public function testPropertyInteresesArteSacro()
    {
    }

    /**
     * Test attribute "ciudad"
     */
    public function testPropertyCiudad()
    {
    }

    /**
     * Test attribute "codigo_postal_empresa"
     */
    public function testPropertyCodigoPostalEmpresa()
    {
    }

    /**
     * Test attribute "intereses_infantiles_juveniles"
     */
    public function testPropertyInteresesInfantilesJuveniles()
    {
    }

    /**
     * Test attribute "intereses_comedores"
     */
    public function testPropertyInteresesComedores()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "nombres"
     */
    public function testPropertyNombres()
    {
    }

    /**
     * Test attribute "giro_construccion"
     */
    public function testPropertyGiroConstruccion()
    {
    }

    /**
     * Test attribute "domicilio"
     */
    public function testPropertyDomicilio()
    {
    }

    /**
     * Test attribute "intereses_servicios"
     */
    public function testPropertyInteresesServicios()
    {
    }

    /**
     * Test attribute "mercado_atiende_construccion"
     */
    public function testPropertyMercadoAtiendeConstruccion()
    {
    }

    /**
     * Test attribute "celular"
     */
    public function testPropertyCelular()
    {
    }

    /**
     * Test attribute "intereses_mueble_oficina"
     */
    public function testPropertyInteresesMuebleOficina()
    {
    }

    /**
     * Test attribute "intereses_recamaras_literas"
     */
    public function testPropertyInteresesRecamarasLiteras()
    {
    }

    /**
     * Test attribute "intereses_tapetes"
     */
    public function testPropertyInteresesTapetes()
    {
    }

    /**
     * Test attribute "intereses_colchones"
     */
    public function testPropertyInteresesColchones()
    {
    }

    /**
     * Test attribute "intereses_mecedoras"
     */
    public function testPropertyInteresesMecedoras()
    {
    }

    /**
     * Test attribute "giro_servicios"
     */
    public function testPropertyGiroServicios()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "apellidos"
     */
    public function testPropertyApellidos()
    {
    }

    /**
     * Test attribute "principal_actividad_otros"
     */
    public function testPropertyPrincipalActividadOtros()
    {
    }

    /**
     * Test attribute "mercado_atiende_residencial"
     */
    public function testPropertyMercadoAtiendeResidencial()
    {
    }

    /**
     * Test attribute "principal_actividad_broker_intermediario"
     */
    public function testPropertyPrincipalActividadBrokerIntermediario()
    {
    }

    /**
     * Test attribute "principal_actividad_venta_publico"
     */
    public function testPropertyPrincipalActividadVentaPublico()
    {
    }

    /**
     * Test attribute "nacimiento"
     */
    public function testPropertyNacimiento()
    {
    }

    /**
     * Test attribute "pais"
     */
    public function testPropertyPais()
    {
    }

    /**
     * Test attribute "giro_tienda_departamental"
     */
    public function testPropertyGiroTiendaDepartamental()
    {
    }

    /**
     * Test attribute "redes_sociales_url_empresa"
     */
    public function testPropertyRedesSocialesUrlEmpresa()
    {
    }

    /**
     * Test attribute "principal_actividad_construccion_hospitalidad"
     */
    public function testPropertyPrincipalActividadConstruccionHospitalidad()
    {
    }

    /**
     * Test attribute "giro_exportador"
     */
    public function testPropertyGiroExportador()
    {
    }

    /**
     * Test attribute "sexo"
     */
    public function testPropertySexo()
    {
    }

    /**
     * Test attribute "principal_actividad_distribuidor"
     */
    public function testPropertyPrincipalActividadDistribuidor()
    {
    }

    /**
     * Test attribute "www_empresa"
     */
    public function testPropertyWwwEmpresa()
    {
    }

    /**
     * Test attribute "mercado_atiende_corporativo"
     */
    public function testPropertyMercadoAtiendeCorporativo()
    {
    }
}
